### PR TITLE
Review fixes and propositions

### PR DESCRIPTION
**Pull request by dgptha**
Various fixes and propositions.

I think that the equations will be better if referenced as done in commit a493768 . Also using floor symbols would be better than saying that the division is an integer division, but for some reason it doesn't display right to me.

### CODE REVIEW

**Comment by ved-rivos** [comment]
Thanks!

**Comment by ved-rivos** [comment]
Unfortunately the floor function does not render for me either.

**Comment by ved-rivos** [comment]
I was able to figure out how to render this symbol.

**Comment by dgptha** [comment]
I know of lfloor and rfloor, but you have to use left and right as in here `\left\lfloor\frac{x}{y}\right\rfloor`, so the floor symbol is correctly sized.
You can see the difference here: [test.pdf](https://github.com/riscv-non-isa/riscv-cmqri/files/11252739/test.pdf)
On the left without `\left` and `\right`, on the right with them.
My problem is that when using them in asciidoctor (using the riscv asciidoctor docker container) the `\left` and `\right` are simply ignored. Maybe it works for you.

**Comment by ved-rivos** [comment]
image

That's right. It renders like this - seems okay.

**Pull request merged**
